from typing import Protocol, Callable

from xo.mark_enum import Mark

class UserIO(Protocol):

    def start_game(self):
        ...
    def stop_game(self):
        ...
    def set_alert(self, alert: str):
        ...
    def fill_location(self, location: tuple[int, int], value: Mark):
        ...
    def stop_alert(self):
        ...
    def subscribe_to_user_input_quit(self, callback: Callable[[None], None]):
        ...
    def subscribe_to_user_input_stop_game(self, callback: Callable[[None], None]):
        ...
    def subscribe_to_user_input_location_fill(self, callback: Callable[[tuple[int, int], Mark], None]):
        ...
    def subscribe_to_user_input_peer(self, callback: Callable[[str], None]):
        ...